# .streamlit/pages.toml

[[pages]]
path = "dashboard.py"
name = "EcoSense"

[[pages]]
path = "chatbot.py"
name = "EcoBot"

[[pages]]
path = "aboutus.py"
name = "About Us"

[[pages]]
path = "privacy_policy.py"
name = "Privacy Policy"

[[pages]]
path = "imprint.py"
name = "Imprint"